#!/usr/bin/env python2.7

'''

check_graphite
Copyright (C) 2016  The project contributors

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <http://www.gnu.org/licenses/>.


'''

import sys
import re
import argparse
import requests
import simplejson as json

EXIT_OK         = 0
EXIT_WARNING    = 1
EXIT_CRITICAL   = 2
EXIT_UNKNOWN    = 3

requests.packages.urllib3.disable_warnings()

def check(host, metric, warning_threshold, critical_threshold,
          invert, function, duration, user, password, grafana, datasourceid, authkey):

    if not host.startswith('http'):
        host = 'http://%s' % host

    critical_threshold = convert_si(critical_threshold)
    if warning_threshold:
        warning_threshold = convert_si(warning_threshold)

    if warning_threshold is not None and warning_threshold > critical_threshold:
        invert = True
    url = '%s/render' % host

    params = {
        'target': metric,
        'format': 'json',
        'from': '-%dmins' % duration,
    }
    if user is not None and password is not None:
        auth = (user, password)
    else:
        auth = None
    try:
        if grafana:
            url = '%s/api/datasources/proxy/%s/render' % (host, datasourceid)
            auth_header = {'Authorization': 'Bearer ' + authkey}
            r = requests.get(url, headers=auth_header, params=params, verify=False)
        else:
            r = requests.get(url, params=params, auth=auth, verify=False)
    except requests.exceptions.ConnectionError, e:
        critical('Failed to contact Graphite server', e.message)
    try:
        data = r.json()
    except json.JSONDecodeError, e:
        critical('Could not decode JSON', r.content)

    try:
        series = [x for x, _ in data[0]['datapoints'] if x is not None]
    except IndexError: # metric does not exist
        critical('Metric %s not found' % metric)
    if len(series) == 0:
        critical('No data for %s' % metric)

    value = apply_function(series, function)

    message = '%s = %s (%s over %s minutes)' % (metric, value, function, duration)
    message = message.replace('|', '_') # everything after | is "performance info"
    info = 'critical %s %s' % ('<' if invert else '>', critical_threshold)
    if warning is not None:
        info += '\nwarning %s %s' % ('<' if invert else '>', warning_threshold)

    if invert:
        if value < critical_threshold:
            critical(message, info)
        if value < warning_threshold:
            warning(message, info)
    else:
        if value > critical_threshold:
            critical(message, info)
        if value > warning_threshold:
            warning(message, info)

    ok(message)

def apply_function(series, function):
    if function == 'max':
        return max(series)
    if function == 'min':
        return min(series)
    if function == 'sum':
        return sum(series)
    if function == 'average':
        return sum(series) / float(len(series))

def critical(message, info=None):
    print 'CRITICAL %s' % message
    if info:
        print '\n%s' % info
    sys.exit(EXIT_CRITICAL)

def warning(message, info=None):
    print 'WARNING %s' % message
    if info:
        print '\n%s' % info
    sys.exit(EXIT_WARNING)

def ok(message, info=None):
    print 'OK %s' % message
    if info:
        print '\n%s' % info
    sys.exit(EXIT_OK)

def unknown(message, info=None):
    print 'UNKNOWN %s' % message
    if info:
        print '\n%s' % info
    sys.exit(EXIT_UNKNOWN)

SI_UNITS = {
    'y': 1e-24,  # yocto
    'z': 1e-21,  # zepto
    'a': 1e-18,  # atto
    'f': 1e-15,  # femto
    'p': 1e-12,  # pico
    'n': 1e-9,   # nano
    'u': 1e-6,   # micro
    'm': 1e-3,   # mili
    'c': 1e-2,   # centi
    'd': 1e-1,   # deci
    '':  1,
    'k': 1e3,    # kilo
    'M': 1e6,    # mega
    'G': 1e9,    # giga
    'T': 1e12,   # tera
    'P': 1e15,   # peta
    'E': 1e18,   # exa
    'Z': 1e21,   # zetta
    'Y': 1e24,   # yotta
}
def convert_si(value):
    if re.search('[0-9][a-zA-Z]$', value):
        unit = value[-1]
        value = value[:-1]
    else:
        unit = ''
    try:
        return float(value) * SI_UNITS[unit]
    except ValueError, KeyError:
        unknown('Failed to parse threshold %s%s' % (value, unit))

if __name__ == '__main__':
    parser = argparse.ArgumentParser('Nagios check for Graphite metrics')
    parser.add_argument('--host', '-o', required=True, help='Graphite host, e.g. graphite.example.com, https://1.2.3.4, graphite01:8080')
    parser.add_argument('--metric', '-m', required=True, help='Metric to check, e.g. web01.processes.fork_rate')
    parser.add_argument('--critical', '-c', required=True, help='Critical threshold, e.g. 1.0, 3G')
    parser.add_argument('--warning', '-w', help='Warning threshold, e.g. -1.1k, 20')
    parser.add_argument('--invert', '-i', action='store_true', help='Invert the check so that an alert is triggered if the value falls below the threshold. Invert is implied if warning threshold > critical threshold')
    parser.add_argument('--duration', '-d', type=int, default=5, help='Number of minutes of data to aggregate')
    parser.add_argument('--function', '-f', default='average', choices=['average', 'max', 'min', 'sum'], help='The aggregation function to apply to the time series')
    parser.add_argument('--user', '-u', help='HTTP auth user')
    parser.add_argument('--password', '-p', help='HTTP auth password')
    parser.add_argument('--grafana', '-g', type=bool, default=False, help='Use grafana datasource proxy {True, False}')
    parser.add_argument('--datasourceid', '-x', type=int, help='Grafana datasource id')
    parser.add_argument('--authkey', '-a', help='Grafana Authorization Key')
    args = parser.parse_args()
    check(host=args.host,
          metric=args.metric,
          warning_threshold=args.warning,
          critical_threshold=args.critical,
          invert=args.invert,
          function=args.function,
          duration=args.duration,
          user=args.user,
          password=args.password,
          grafana=args.grafana,
          datasourceid=args.datasourceid,
          authkey=args.authkey)
